```bash
name: production testing pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build, Test & Deploy Portfolio
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Files Exist
      run: |
        test -f index.html || (echo "index.html missing" && exit 1)
        test -f style.css || (echo "style.css missing" && exit 1)
        test -f script.js || (echo "script.js missing" && exit 1)

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AKIAWX6GPYXF7NNFQLVD }}
        aws-secret-access-key: ${{ secrets.iNBTonA8gs+S6SeyMjzgzrpx8ilU4P1Dwj71deiQ }}
        aws-region: 'ap-south-1'

    - name: Deploy to S3
      run: |
        aws s3 sync s3://${{ secrets.devops-cicdproject }} --delete

```
